### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Find top-down car img.
- [x] Find background img.
- [x] Create an HTML  skeleton fit for the program.
- [x] Use CSS for any editing.
- [x] Check for useless code and bugs.
- [x] Final Check
