### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] querySelect the proper classes
- [x] Determine the direction the car faces
- [x] Make sure code runs without errors
- [x] Check for any useless CSS and delete them
- [x] Final Check
