### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for car image.
- [x] Use the style property of element objects to change the car's top and left box offset styles.
- [x] Move the car every 16 milliseconds for a smooth movement.
- [x]  Check for useless css and html code 
- [x] Final check
