### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add Boolean to Code
- [x] Check for unused code in html. css and javascript files
- [x] Run code and check for bugs
