### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Find out which direction car is in
- [x] Create a function that determines the direction and adds input 
- [x] Check for bugs and useless code
- [x] Final Check
